#ifndef _COMMON_DEF_H_
#define _COMMON_DEF_H_


#define APP_VERSION 1.0
#define DEFAULT_SERVER_IP "127.0.0.1"
#define DEFAULT_SERVER_PORT 8988

#define TCP_PORT_MIN 0
#define TCP_PORT_MAX 65535

#define PROCESS_MIN_POLL_INTERVAL 500
#define PROCESS_DEFAULT_POLL_INTERVAL 2000
#define PROCESS_MAX_POLL_INTERVAL 60000

#define MAX_PDU_BUFFER_LENGTH 4200

#define PROCESS_CONFIG_DEFAULT_FILE_NAME "process_configuration.xml"
#define PROCESS_CONFIG_DEFAULT_VERSION "1.0"
#define PROCESS_CONFIG_DEFAULT_GROUP_ID "default"

#define SERVER_CONFIG_DEFAULT_FILE_NAME "pms.config"
#define SERVER_CONFIG_DEFAULT_LOG_PATH "./logs/log.log"

#define CLIENT_CONFIG_DEFAULT_FILE_NAME "pmc.config"

#endif